### ISSUE TITLE
In the script the BlobSize =256 is not included which is getting the Blobsize as 512 even if the file size is 256 GB.

### ISSUE THREAD

**Issue by akshaysanadhya1e** [dimitri-furman/managed-instance#7] opened 2022-03-10 08:30 UTC
In the script the BlobSize =256 is not included which is getting the Blobsize as 512 even if the file size is 256 GB. Highlighted bold is missing in the script.
SELECT 128 AS BlobSizeGB, 500 AS IOPSLimit, 100 AS ThroughputLimit
UNION
_**SELECT 256 AS BlobSizeGB, 1100 AS IOPSLimit, 125 AS ThroughputLimit**_
UNION
SELECT 512, 2300, 150
UNION
SELECT 1024, 5000, 200
UNION
SELECT 2048, 7500, 250
UNION
SELECT 4096, 7500, 250
UNION
SELECT 8192, 12500, 480

**Comment by dimitri-furman** [comment] 2022-03-10 20:43
Duplicate of #3

**Closed as completed by dimitri-furman** 2022-03-10 20:43 UTC
Labels: duplicate
